version: '3.8'

services:
  # Backend Laravel API
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: music-api
    ports:
      - "8000:80"
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
    volumes:
      - ./api:/var/www/html
      - api_storage:/var/www/html/storage
    networks:
      - music-network
    restart: unless-stopped

  # Frontend React/Vite
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: music-web
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - music-network
    restart: unless-stopped

  # Development frontend (for hot reload)
  frontend-dev:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: music-web-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - music-network
    profiles:
      - dev
    restart: unless-stopped

volumes:
  api_storage:

networks:
  music-network:
    driver: bridge
